name: CI
on: 
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      Deploy:
        description: 'Manual deployment'     
        required: true
        default: 'Manual'
permissions:
      id-token: write
      contents: read

jobs: 
  Deploy-VM:
    runs-on: ubuntu-latest
    environment: QA
    steps:
      
      #- uses: actions/checkout@v3
      
      - name: Azure Login
        uses: Azure/login@v1.4.5
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          client-id: ${{secrets.CLIENTID}}
          tenant-id: ${{secrets.TENANTID}}
          subscription-id: ${{secrets.Subscription_ID}}
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az account show

#       - name: 'Run az commands'
#         run: |
#           az account show

#       - name: Deploy Azure Resource Manager (ARM) Template
#         uses: Azure/arm-deploy@v1.0.8
#         with:
#           subscriptionId:
#           resourceGroupName:
#           template: 
#           deploymentMode:
#           parameters:
